name: xcodegen-trial
options:
  bundleIdPrefix: com.yani
targets:
  xcodegen-trial:
    type: application
    platform: iOS
    deploymentTarget: 17.0
    sources:
      - xcodegen-trial
    settings:
      MARKETING_VERSION: 1.0
      CURRENT_PROJECT_VERSION: 1
      SWIFT_VERSION: 5.0
      PRODUCT_BUNDLE_IDENTIFIER: "com.yani.xcodegen-trial"
      ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
      ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
      CODE_SIGN_STYLE: Automatic
      CURRENT_PROJECT_VERSION: 1
      DEVELOPMENT_TEAM: Y6X9S45TDJ
      GENERATE_INFOPLIST_FILE: YES
      INFOPLIST_FILE: "xcodegen-trial/Info.plist"
      INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: YES
      INFOPLIST_KEY_UILaunchStoryboardName: LaunchScreen
      INFOPLIST_KEY_UIMainStoryboardFile: Main
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
      LD_RUNPATH_SEARCH_PATHS: ("$(inherited)","@executable_path/Frameworks",)
      MARKETING_VERSION: 1.0
      PRODUCT_NAME: "$(TARGET_NAME)"
      SWIFT_EMIT_LOC_STRINGS: YES
      TARGETED_DEVICE_FAMILY: "1,2"
